compile:
	g++ -o addtwo.exe src/main.cpp src/functions.cpp

run: compile
	./addtwo.exe

clean:
	rm addtwo.exe

unittest:
	g++ -o test_function.exe src/functions.cpp src/test_functions.cpp
	./test_function.exe

